# Generated by Django 5.2.1 on 2025-05-25 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.area'),
        ),
    ]
