# Generated by Django 5.2.1 on 2025-05-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_user',
            field=models.CharField(choices=[('economico', 'Económico'), ('jefe_area', 'Jefe de Área'), ('admin_sitio', 'Administrador del sitio')], max_length=11),
        ),
    ]
