# Generated by Django 5.2.1 on 2025-05-25 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_usuario_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='area',
            field=models.ForeignKey(default='Sin Area', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.area'),
        ),
    ]
