# Generated by Django 5.2.1 on 2025-05-26 13:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_usuario_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Área', 'verbose_name_plural': 'Áreas'},
        ),
        migrations.AlterModelOptions(
            name='solicitudesproductos',
            options={},
        ),
        migrations.RemoveField(
            model_name='solicitudesproductos',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='solicitudesproductos',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='solicitudesproductos',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='solicitudesproductos',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 26, 9, 22, 28, 391131)),
        ),
        migrations.AddField(
            model_name='solicitudesproductos',
            name='items',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='solicitudesproductos',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.area'),
        ),
    ]
