# Generated by Django 5.2.1 on 2025-05-30 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_area_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='producto',
        ),
        migrations.AddField(
            model_name='inventario',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2025, 5, 30, 13, 20, 36, 214906)),
        ),
        migrations.AddField(
            model_name='inventario',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='inventario-files/'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='inventario-imgs/'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='proveedores/'),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='estado',
            field=models.CharField(choices=[('dado_de_baja', 'Dado de baja'), ('en_uso', 'En uso'), ('almacen', 'Almacen'), ('en_reparacion', 'En reparación')], max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitudesproductos',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 30, 13, 20, 36, 215950)),
        ),
    ]
