# Generated by Django 5.2.1 on 2025-05-30 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_activofijo_inventario_alter_activofijo_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activofijo',
            name='estado',
            field=models.CharField(choices=[('en_reparacion', 'En reparación'), ('dado_de_baja', 'Dado de baja'), ('almacen', 'Almacen'), ('en_uso', 'En uso')], max_length=30),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='fecha_adquisicion',
            field=models.DateField(default=datetime.datetime(2025, 5, 30, 13, 45, 11, 471523)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2025, 5, 30, 13, 45, 11, 471181)),
        ),
        migrations.AlterField(
            model_name='solicitudesproductos',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 30, 13, 45, 11, 472671)),
        ),
    ]
