# Generated by Django 5.2.1 on 2025-05-31 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_activofijo_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activofijo',
            name='inventario',
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='estado',
            field=models.CharField(choices=[('en_uso', 'En uso'), ('en_reparacion', 'En reparación'), ('dado_de_baja', 'Dado de baja'), ('almacen', 'Almacen')], max_length=30),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='fecha_adquisicion',
            field=models.DateField(default=datetime.datetime(2025, 5, 31, 8, 23, 39, 81500)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2025, 5, 31, 8, 23, 39, 81253)),
        ),
        migrations.AlterField(
            model_name='solicitudesproductos',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudesproductos',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 31, 8, 23, 39, 82277)),
        ),
    ]
