# Generated by Django 5.2.1 on 2025-05-31 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_remove_activofijo_inventario_alter_activofijo_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='estado',
            field=models.CharField(choices=[('en_uso', 'En uso'), ('en_reparacion', 'En reparación'), ('almacen', 'Almacen'), ('dado_de_baja', 'Dado de baja')], max_length=30),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='fecha_adquisicion',
            field=models.DateField(default=datetime.datetime(2025, 5, 31, 10, 38, 22, 185394)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2025, 5, 31, 10, 38, 22, 185123)),
        ),
        migrations.AlterField(
            model_name='solicitudesproductos',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 31, 10, 38, 22, 186157)),
        ),
    ]
