# Generated by Django 5.2.1 on 2025-05-31 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_producto_serial_number_alter_activofijo_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='activofijo',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='estado',
            field=models.CharField(choices=[('en_reparacion', 'En reparación'), ('almacen', 'Almacen'), ('dado_de_baja', 'Dado de baja'), ('en_uso', 'En uso')], max_length=30),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='fecha_adquisicion',
            field=models.DateField(default=datetime.datetime(2025, 5, 31, 12, 1, 0, 913217)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2025, 5, 31, 12, 1, 0, 912926)),
        ),
        migrations.AlterField(
            model_name='solicitudesproductos',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 31, 12, 1, 0, 914041)),
        ),
    ]
