# Generated by Django 5.2.1 on 2025-05-31 20:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_remove_producto_serial_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.area'),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='estado',
            field=models.CharField(choices=[('almacen', 'Almacen'), ('en_reparacion', 'En reparación'), ('dado_de_baja', 'Dado de baja'), ('en_uso', 'En uso')], max_length=30),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='fecha_adquisicion',
            field=models.DateField(default=datetime.datetime(2025, 5, 31, 16, 25, 47, 88349)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2025, 5, 31, 16, 25, 47, 88076)),
        ),
        migrations.AlterField(
            model_name='solicitudesproductos',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 31, 16, 25, 47, 89134)),
        ),
    ]
