# Generated by Django 5.2.1 on 2025-05-31 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_ubicacion_area_alter_activofijo_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activofijo',
            name='estado',
            field=models.CharField(choices=[('en_reparacion', 'En reparación'), ('en_uso', 'En uso'), ('dado_de_baja', 'Dado de baja'), ('almacen', 'Almacen')], max_length=30),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='fecha_adquisicion',
            field=models.DateField(default=datetime.datetime(2025, 5, 31, 16, 25, 53, 827271)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2025, 5, 31, 16, 25, 53, 826999)),
        ),
        migrations.AlterField(
            model_name='solicitudesproductos',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 31, 16, 25, 53, 828059)),
        ),
    ]
