# Generated by Django 5.2.1 on 2025-07-04 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_alter_activofijo_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activofijo',
            name='valor_adquisicion',
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='estado',
            field=models.CharField(choices=[('almacen', 'Almacen'), ('dado_de_baja', 'Dado de baja'), ('en_reparacion', 'En reparación'), ('en_uso', 'En uso')], max_length=30),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='fecha_adquisicion',
            field=models.DateField(default=datetime.datetime(2025, 7, 4, 11, 55, 35, 537022)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2025, 7, 4, 11, 55, 35, 536749)),
        ),
        migrations.AlterField(
            model_name='solicitudesproductos',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 4, 11, 55, 35, 537872)),
        ),
    ]
