# Generated by Django 5.2.1 on 2025-07-04 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_remove_activofijo_valor_adquisicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activofijo',
            name='estado',
            field=models.CharField(choices=[('En uso', 'En Uso'), ('Almacen', 'Almacen'), ('En reparación', 'En Reparacion'), ('Dado de baja', 'Dado De Baja')], default='Almacen', max_length=30),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='fecha_adquisicion',
            field=models.DateField(default=datetime.datetime(2025, 7, 4, 12, 51, 58, 246604)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2025, 7, 4, 12, 51, 58, 246155)),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida'), ('Ajuste', 'Ajuste')], max_length=10),
        ),
        migrations.AlterField(
            model_name='solicitudesproductos',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudesproductos',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 4, 12, 51, 58, 247196)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_user',
            field=models.CharField(choices=[('Económico', 'Economico'), ('Jefe de Área', 'Jefe Area'), ('Administrador del sitio', 'Admin Sitio')], max_length=23),
        ),
    ]
