# Generated by Django 5.2.1 on 2025-07-04 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_alter_activofijo_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activofijo',
            name='fecha_adquisicion',
            field=models.DateField(default=datetime.datetime(2025, 7, 4, 12, 53, 48, 502069)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2025, 7, 4, 12, 53, 48, 501692)),
        ),
        migrations.AlterField(
            model_name='solicitudesproductos',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 4, 12, 53, 48, 502886)),
        ),
    ]
