# Generated by Django 5.2.1 on 2025-07-04 20:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_alter_activofijo_fecha_adquisicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activofijo',
            name='fecha_adquisicion',
            field=models.DateField(default=datetime.datetime(2025, 7, 4, 16, 43, 26, 417334)),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='ubicacion',
            field=models.ForeignKey(default='-----------', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.ubicacion'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2025, 7, 4, 16, 43, 26, 417068)),
        ),
        migrations.AlterField(
            model_name='solicitudesproductos',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 4, 16, 43, 26, 418214)),
        ),
    ]
