# Generated by Django 5.2.1 on 2025-07-12 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_alter_activofijo_fecha_adquisicion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activofijo',
            name='responsable',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='users-img/'),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='codigo_interno',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
