# Generated by Django 5.2.1 on 2025-07-13 19:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_activofijo_responsable_usuario_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('accion', models.CharField(choices=[('Mantenimiento', 'Mantenimiento'), ('Movimiento de Área', 'Movimiento De Area'), ('Cambio de responsable', 'Cambio De Responsable'), ('Otros', 'Otros')], max_length=25)),
                ('estado', models.CharField(choices=[('Completado', 'Completado'), ('Proceso', 'Proceso'), ('Fallido', 'Fallido')], max_length=20)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.activofijo')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
