# Generated by Django 5.2.1 on 2025-07-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_historialactivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activofijo',
            name='estado',
            field=models.CharField(choices=[('En uso', 'En Uso'), ('Almacen', 'Almacen'), ('En reparación', 'En Reparacion'), ('Dado de baja', 'Dado De Baja')], default='En uso', max_length=30),
        ),
    ]
