# Generated by Django 5.2.1 on 2025-07-25 02:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_alter_activofijo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activofijo',
            name='estado',
            field=models.CharField(choices=[('En uso', 'En Uso'), ('Almacen', 'Almacen'), ('En reparación', 'En Reparacion'), ('Dado de baja', 'Dado De Baja')], default='Almacen', max_length=30),
        ),
        migrations.AlterField(
            model_name='historialactivo',
            name='accion',
            field=models.CharField(choices=[('Mantenimiento', 'Mantenimiento'), ('Movimiento de Área', 'Movimiento De Area'), ('Cambio de responsable', 'Cambio De Responsable'), ('Dado de baja', 'Dado De Baja'), ('Otros', 'Otros')], max_length=25),
        ),
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.historialactivo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
    ]
