# Generated by Django 5.2.1 on 2025-07-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_alter_activofijo_estado_alter_historialactivo_accion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertas',
            name='stock',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='alertas',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
