# Generated by Django 5.2.1 on 2025-07-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0022_alertas_stock_alertas_stock_minimo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertas',
            options={'verbose_name_plural': 'Alertas'},
        ),
        migrations.AlterModelOptions(
            name='historialactivo',
            options={'verbose_name_plural': 'Historial de Activos'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='solicitudesproductos',
            options={'verbose_name_plural': 'Solicitudes de Productos'},
        ),
        migrations.AddField(
            model_name='historialactivo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='estado',
            field=models.CharField(choices=[('En uso', 'En Uso'), ('Almacen', 'Almacen'), ('En reparación', 'En Reparacion'), ('Dado de baja', 'Dado De Baja'), ('Sin ubicación', 'Sin Ubicacion')], default='Almacen', max_length=30),
        ),
    ]
