# Generated by Django 5.2.1 on 2025-08-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_alter_alertas_options_alter_historialactivo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activofijo',
            name='estado',
            field=models.CharField(choices=[('En uso', 'En Uso'), ('Almacen', 'Almacen'), ('En reparación', 'En Reparacion'), ('Dado de baja', 'Dado De Baja'), ('Sin ubicación', 'Sin Ubicacion'), ('PERRA', 'Perra')], default='Almacen', max_length=30),
        ),
        migrations.AlterField(
            model_name='area',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
