# Generated by Django 5.2.1 on 2025-10-18 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_alter_activofijo_estado_alter_area_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertas',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.area'),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='estado',
            field=models.CharField(choices=[('En uso', 'En Uso'), ('Almacen', 'Almacen'), ('En reparación', 'En Reparacion'), ('Dado de baja', 'Dado De Baja'), ('Sin ubicación', 'Sin Ubicacion')], default='Almacen', max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_user',
            field=models.CharField(choices=[('Trabajador', 'Trabajador'), ('Económico', 'Economico'), ('Jefe de Área', 'Jefe Area'), ('Administrador del sitio', 'Admin Sitio')], max_length=23),
        ),
    ]
